## you probably need to change or comment/uncomment some of these
#
# The working dir... output will be in the results subfolder of the workdir
workdir: "WORKDIR"
# if you change resourcedir then the snakemake calls in the wrapper script will also need to be changed.
# commenting out the following line uses the resources folder in WORKDIR
resourcesdir: "WORKRESOURCESDIR"
scriptsdir: "WORKSCRIPTSDIR"
#
# tab delimited samples file ... should have the following 3 columns
# sampleName	replicateNumber	path_to_R1_fastq
# samples need to have atleast 2 replicates
#
samplemanifest: "WORKDIR/samples.tsv"


# trimming details
illumina_sequencing_adapter: "GATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNNTCTCGTATGCCGTCTTCTGCTTG"  # generic illumin seq adapter
linker: "NNNNNNCACTCGGGCACCAAGGA"                                                               # linker sequence
n5trim: "4"                                                                                     # number of bases to trim from 5prime end
nextseq_trim_q: "15"                                                                            # min. len. after trimming
minlen: "10"                                                                                    # min. len. after trimming